# Generated by Django 3.1.3 on 2021-08-18 15:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210817_1737'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsfeed',
            unique_together={('user', 'tweet')},
        ),
    ]
